source "https://rubygems.org"

gem "serialport", "~> 1.3"

gem "sinatra", ">= 3.1"
gem "rackup", ">= 2.1"
gem "puma", ">= 6.4"
gem "bcrypt", "~> 3.1"
gem "dotenv", "~> 3.1"

group :test do
  gem "minitest", ">= 5.0"
  gem "rack-test", "~> 2.1"
  gem "rake"
end
